source "http://rubygems.org"

gem "adhearsion", :git => 'git://github.com/adhearsion/adhearsion.git', :branch => :develop

#
# Here are some example components you might like to use. Simply
# uncomment them, run `bundle install` and enable in startup.rb.
#

# gem 'ahn-restful-rpc'
