source "http://rubygems.org"

gem "adhearsion", :git => 'git://github.com/adhearsion/adhearsion.git', :branch => :develop

#
# Here are some example plugins you might like to use. Simply
# uncomment them and run `bundle install`.
#

# gem 'ahn-asterisk'
