#!/usr/bin/env ruby

def check_ragel_version
  ragel_version_match = `ragel --version`.match(/(\d)\.(\d)+/)
  abort "Could not get Ragel version! Is it installed? You must have at least version 6.3" unless ragel_version_match
  big, small = ragel_version_match.captures.map { |n| n.to_i }
  if big < 6 || (big == 6 && small < 3)
    abort "Please upgrade Ragel! You're on version #{ragel_version_match[0]} and must be on 6.3 or later"
  end
end

def ragel_to_ruby
  check_ragel_version
  ragel_file = File.dirname(__FILE__) + "/ami.rl"
  ruby_output = ragel_file[0..-2] + 'b'
  puts `ragel -n -R #{ragel_file}`
  
  comment = '# THIS FILE WAS AUTOMATICALLY GENERATED BY RAGEL. DO NOT MODIFY!'
  code = File.read(ruby_output).split "\n"
  File.open ruby_output, "w" do |file|
    until code.empty?
      file.puts code.shift
      file.puts comment
    end
  end
end

ragel_to_ruby if $0 == __FILE__
