require 'rubygems'
require 'spec/story'
require File.dirname(__FILE__) + "/../../../lib/adhearsion"
require 'adhearsion/voip/asterisk/new-ami/ami'

RAGEL_FILES = %W[lib/adhearsion/voip/asterisk/new-ami/ami.rl]

def regenerate_ragel
  # Check Ragel version:
  ragel_version_match = `ragel --version`.match(/(\d)\.(\d)+/)
  abort "Could not get Ragel version! Is it installed? You must have at least version 6.3" unless ragel_version_match
  big, small = ragel_version_match.captures.map { |n| n.to_i }
  if big < 6 || (big == 6 && small < 3)
    abort "Please upgrade Ragel! You're on version #{ragel_version_match[0]} and must be on 6.3 or later"
  end
  
  RAGEL_FILES.each do |ragel_file|
    ruby_file  = ragel_file[0..-2] + "b"
    
    # Generate output
    puts `ragel -n -R #{ragel_file} -o #{ruby_file} 2>&1`
  
    # comment = '# THIS FILE WAS AUTOMATICALLY GENERATED BY RAGEL. DO NOT MODIFY!'
    # code = File.read(ruby_file).split "\n"
    # File.open ruby_file, "w" do |file|
    #   until code.empty?
    #     file.puts code.shift
    #     file.puts comment
    #   end
    # end
  end
end

Dir.chdir(File.dirname(__FILE__) + "/../../..") { regenerate_ragel }