on: push

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', 'jruby-9.4', 'jruby-head']

    env:
      RAILS_ENV: test
      CI: true
      JRUBY_OPTS: "-J-Xmx512m"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Specs
        run: |
          bundle exec rspec spec
          ruby -v | grep jruby || bundle exec cucumber features

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
